### ISSUE TITLE
builder does not work with ES6 module format

### ISSUE THREAD

**Issue by larryhe** [yoavniran/grunt-systemjs-builder#10]
Hi there 
Do you have a working example that has ES6 module format. Looks like it does not work well with transpiler (like babel). Thanks for  your time.

**Comment by yoavniran** [comment]
hi @larryhe 
I created a simple test using ES6 with Babel and the build went successfully.
you can see the test here: https://github.com/yoavniran/grunt-systemjs-builder/tree/master/tests/babel

can you elaborate whats failing for you?
thanks.

**Comment by larryhe** [comment]
Hi @yoavniran  thanks for your quick reply. Looks like you also use JSPM to automatically generate config file. that's all the problem I had. If I use JSPM config, it works fine. But it does not work with simple SystemJS/SystemBuilder config from their documentations. Seems that JSPM does a lot of complicated stuffs behind the scene. because I don't want to use JSPM to manage the packages(We use bower here)  and just want to use SystemJS and SystemBuilder. I don't figure it out yet.  Also I notice this grunt extent ion is based on SystemJS builder, If it has to use JSPM stuff to make it work with ES6, why don't you use JSPM API directly? (http://jspm.io/docs/api.html) THANKS for your time.

**Comment by yoavniran** [comment]
hi @larryhe to answer your second question first, the JSPM API isnt stable (see the first lines in the link you sent).
The System JS builder API is much more stable, better documented (though still lacking) and provides more functionality.

I havent considered a scenario of using SystemJS + Builder without initializing using JSPM so far. I think your issue here is less related to this project and more to incorrect configuration.

Nevertheless, I would love to support your scenario if its possible. What errors do you get? How does your configuration look like?

**Comment by larryhe** [comment]
Hi @yoavniran thanks for your reply. Basically i followed example here (https://github.com/systemjs/builder) and my simple configuration is as below. but it did not work. according to SystemBuilder documentation, it should work without depending on JSPM. 

```
//my config.js
System.config({
  baseURL: "./",
  defaultJSExtensions: true,
  transpiler: "babel",
  paths: {
      'babel': './node_modules/babel-core/index.js'
  }
});
```

If I use JSPM automatically generated configuration (like your example), It works fine. But this will make your project highly tied with JSPM and jspm_packages stuffs, that I do not want. So my question is if it's possible to build a project based on SystemJS and SystemBuilder only. Thanks for your time.

**Comment by yoavniran** [comment]
@larryhe as I suspected, its a matter of correct configuration.
see the example I just pushed ([config.js](https://github.com/yoavniran/grunt-systemjs-builder/blob/master/tests/nojspm/config.js)) shows how to tell the builder where to find babel without jspm.

thanks for sharing your issue here.
