### ISSUE TITLE
Support to update to latest systemjs builder version of 0.16? 

### ISSUE THREAD

**Issue by og-neth** [yoavniran/grunt-systemjs-builder#12]
When will this grunt task be updated to support the latest 0.16.+ releases of systemjs-builder?

**Comment by yoavniran** [comment]
hi @og-neth this task currently supports versions of SystemJS Builder 0.15.x which matches the latest release (0.15.10).

Im not aware of 0.16.+ releases...? https://github.com/systemjs/builder/releases

**Comment by og-neth** [comment]
@yoavniran yeah, I brought that up due to this comment here: [https://github.com/jspm/jspm-cli/issues/1555#issuecomment-188861306](https://github.com/jspm/jspm-cli/issues/1555#issuecomment-188861306)

**Comment by og-neth** [comment]
@yoavniran I just deleted my grunt-systemjs-builder module and reloaded it and the output console in my Visual Studio IDE says it loaded version 0.14.15, how can I verify that the task is loading version 0.15.10 + ?? 

```
grunt-systemjs-builder@0.2.5 node_modules\grunt-systemjs-builder
└── systemjs-builder@0.14.15 (mkdirp@0.5.1, glob@6.0.4, source-map@0.5.3, bluebird@3.3.3, uglify-js@2.6.2, traceur@0.0.93, systemjs@0.19.9, es6-template-strings@2.0.0)
```

I also looked in the package.json of the grunt-systemjs-builder in my node modules and it looks like it's pointing to a previous version as well...

```
"dependencies": {
    "systemjs-builder": "^0.14.11"
  },
```

**Comment by yoavniran** [comment]
sorry @og-neth my bad. I tested against 0.15.x and committed to master but didnt release the update yet. Now I have. please upgrade this task to 0.2.6 and you should have the update to the supported Builder version. Let me know how it goes.

**Comment by og-neth** [comment]
@yoavniran it worked now with the updated systemjs-builder node module I no longer get the error in my browser, thanks man, however the bundling is super slow, I am working with KendoUI framework and systemjs, here is what my main app.core.js file looks like:

```
import 'app.config';
import 'kendo.core.min';
import 'kendo.binder.min';
import 'kendo.dropdownlist.min';
import 'kendo.datepicker.min';
import 'kendo.grid.min';
import 'kendo.window.min';
import 'kendo.calendar.min';
import 'kendo.columnsorter.min';
import 'kendo.editable.min';
import 'kendo.filtermenu.min';
import 'kendo.columnmenu.min';
import 'kendo.groupable.min';
import 'kendo.popup.min';
import 'kendo.data.min';
import 'kendo.draganddrop.min';
import 'kendo.list.min';
import 'kendo.mobile.scroller.min';
import 'kendo.userevents.min';
import 'kendo.fx.min';
import 'kendo.data.odata.min';
import 'kendo.data.xml.min';
import 'kendo.pager.min';
import 'kendo.selectable.min';
import 'kendo.sortable.min';
import 'kendo.reorderable.min';
import 'kendo.resizable.min';
import 'kendo.mobile.actionsheet.min';
import 'kendo.mobile.pane.min';
import 'kendo.ooxml.min';
import 'kendo.excel.min';
import 'kendo.progressbar.min';
import 'kendo.pdf.min';
import 'kendo.numerictextbox.min';
import 'kendo.validator.min';
import 'kendo.menu.min';
import 'kendo.mobile.view.min';
import 'kendo.mobile.loader.min';
import 'kendo.mobile.popover.min';
import 'kendo.mobile.shim.min';
import 'kendo.view.min';
import 'kendo.drawing.min';
import 'kendo.color.min';
```

But the Task Runner Explorer in my Visual Studio IDE reports the following metric

```
>> File "Scripts\app\app.core.js" changed.
Running "systemjs:dist" (systemjs) task
Running "watch" task
Completed in 442.273s at Tue Mar 08 2016 21:24:00 GMT-0800 (Pacific Standard Time) - Waiting...

```

Any ideas is this a grunt issue or systemjs-builder issue?

**Comment by yoavniran** [comment]
hey @og-neth , I doubt this is a grunt issue as its simply handing the config to the systemjs builder to do the work.
I suggest trying out the bundling with JSPM directly ([docs](https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md#creating-a-bundle))

I expect youd see the same build times.

**Comment by og-neth** [comment]
@yoavniran man thank you so much for responding so quickly. That is good insight, at least for now it is working and I can trigger the task to run during building instead of on save to make my development workflow more efficient, thanks for updating the package, because now I'm able to bundle.
