### ISSUE TITLE
How do I set defaultExtension?

### ISSUE THREAD

**Issue by XanderEmu** [yoavniran/grunt-systemjs-builder#16]
How do I set defaultExtension? In regular in-browser systemjs I set it up in package configuration. With grunt-systemjs-builder there are no packages, so how do I tell it to use '.js' as default extension?

**Comment by yoavniran** [comment]
Hi @XanderEmu , the best way is to use your configuration file.
you do this by setting options-configFile property.
you can see it in the example code: https://github.com/yoavniran/grunt-systemjs-builder/blob/master/tests/example/gruntfile.js#L10

**Comment by XanderEmu** [comment]
I see. Thanks :)
