### ISSUE TITLE
Fatal error: ENOENT: no such file or directory, open '/js/undefined.js'

### ISSUE THREAD

**Issue by richburdon** [yoavniran/grunt-systemjs-builder#3]
Fails with simple config.

```
systemjs: {
  demo: {
    options: {
      configFile: 'src/main/javascript/config.js',
      minify: false,
      sfx: false
    },
    files: [{
      src:  'app/demo/main.js',
      dest: 'src/main/javascript/min/demo/demo.min.js'
    }]
  }
},
```

**Comment by gurdotan** [comment]
Same problem here...

**Comment by yoavniran** [comment]
hey @richburdon and @gurdotan 

I've created a test folder (see: https://github.com/yoavniran/grunt-systemjs-builder/tree/master/tests/example) with a similar set up based on the supplied gruntfile excerpt.
running grunt on it works without an error on my machine.

Please have a look and check what could be the differences between what I did and what you did that can maybe explain the error.

Also, please try running with grunt in --verbose to get a bit more info while running the task.

thanks.

**Comment by gurdotan** [comment]
@yoavniran thanks for this but it might take me a while to get to it since I started evaluating another module loader

**Comment by MisterFreeze** [comment]
I'm experiencing the same erroneous behavior here. file.src is not an array, will make a pull request. :)

**Comment by yoavniran** [comment]
hi @MisterFreeze can you share your gruntfile? 
thanks

**Comment by MisterFreeze** [comment]
Sorry that was a too quick shot. In the grunt task, each object in `this.files` has an empty array as value for `src` and an additinal `orig` value containing the original `src` and `dest` value, if the `src` file does not exist.

I made a typo in my config file and gave an invalid path.

This is what I get when calling `console.log(JSON.stringify(this.files))` in `task()`:
<code><pre>[  
   {  
      "src":[
      ],
      "dest":"./static/js/tok-layout-bundle.js",
      "orig":{  
         "src":[  
            "./static/js/tok-layout.js"
         ],
         "dest":"./static/js/tok-layout-bundle.js"
      }
   }
]</pre></code>

I think raising an error if src[0] is undefined would help me to avoid this mistake in the future. :)

Thanks for your great work, @yoavniran
