### ISSUE TITLE
done() called too early if more than one file is to be built

### ISSUE THREAD

**Issue by MisterFreeze** [yoavniran/grunt-systemjs-builder#5]
The `done` callback, the result of the grunt task's `this.async()`, is passed to the `_buildSource` call for each file of `this.files`. `done` will be called after the first successful `builder`'s run, resulting in only one element of `this.files` being processed.

This is an example of `grunt --verbose` for two objects in `files`:

```
systemjs-builder-task - running build method: buildSFX
systemjs-builder-task - about to build source: ./static/js/tok-config-tree.js
systemjs-builder-task - about to build source: ./static/js/tok-main.js
systemjs-builder-task - finished building source: ./static/js/tok-main.js

Done, without errors.
```

Maybe `Q.all` of  could come in handy here.

**Comment by MisterFreeze** [comment]
rsvp.js is used by system-builder. seems to also offer this functionality.

**Comment by yoavniran** [comment]
thanks @MisterFreeze for making me aware of this issue!
i quickly solved it without having to introduce another library (rsvp)

**Comment by MisterFreeze** [comment]
Thank you!
