### ISSUE TITLE
Should `ignoreBaseUrlInConfFile`'s value be `!!options.baseURL`

### ISSUE THREAD

**Issue by MisterFreeze** [yoavniran/grunt-systemjs-builder#8]
Hello all!

After a recent update, my config.js's baseURL does not seem to be honored anymore. I realized that there is a new option to `builder.loadConfig`, named `ignoreBaseUrlInConfiFile`. It's value is `!!options.configFile` in a block that is executed depending on `options.configFile`.

From how I understand the code, `ignoreBaseUrlInConfiFile`'s value should be `!!options.baseURL`.

**Comment by yoavniran** [comment]
you are very correct @MisterFreeze, sorry for the inconvenience 
thanks for notifying right away. For some reason im not getting email notifications about issues opened in this repo so didnt see til' now...

**Comment by MisterFreeze** [comment]
Thank you for the fix, @yoavniran.
